# Generated by Django 5.2.16 on 2026-09-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
