# Generated by Django 5.2.16 on 2026-09-09 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_cycle_closed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('complete', 'Complete'), ('reopened', 'Reopened')], max_length=10)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certifications', to='hub.requirement')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
