# Generated by Django 5.2.16 on 2026-09-25 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_requirements_legacy(apps, schema_editor):
    # Existing item-level history stays in its original tables. This flag only
    # permits its legacy API path until a Coordinator/contributor starts a package.
    apps.get_model('hub', 'Requirement').objects.all().update(legacy_submission_mode=True)


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_legacy_submission_criteria_unknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='legacy_submission_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PackageAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('revisions_requested', 'Revisions requested'), ('withdrawn', 'Withdrawn')], default='draft', max_length=22)),
                ('notes', models.TextField(blank=True)),
                ('criteria_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('criteria_snapshot', models.JSONField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_attempts', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='hub.requirement')),
                ('source_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hub.packageattempt')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='CertificationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='hub.requirementcertification')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.packageattempt')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('approved', 'Approved'), ('revisions_requested', 'Revisions requested')], max_length=22)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='hub.packageattempt')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.evidencemapping')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='hub.packageattempt')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='hub.documentversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='packageattempt',
            constraint=models.UniqueConstraint(fields=('requirement', 'number'), name='package_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='packageattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'submitted')), fields=('requirement',), name='one_submitted_package_per_requirement'),
        ),
        migrations.AddConstraint(
            model_name='certificationpackage',
            constraint=models.UniqueConstraint(fields=('certification', 'package'), name='unique_certification_package'),
        ),
        migrations.AddConstraint(
            model_name='packageitem',
            constraint=models.UniqueConstraint(fields=('package', 'mapping'), name='package_mapping_once'),
        ),
        migrations.AddConstraint(
            model_name='packageitem',
            constraint=models.UniqueConstraint(fields=('package', 'version'), name='package_version_once'),
        ),
        migrations.RunPython(mark_existing_requirements_legacy),
    ]
