# Generated by Django 5.2.16 on 2026-09-26 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_authratebucket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-id'], 'permissions': [('view_security_audit', 'Can view institution security audit events')]},
        ),
    ]
