# Generated by Django 5.2.16 on 2026-10-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_archive_lifecycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycle',
            options={'permissions': [('provision_cycle', 'Can provision an initial cycle')]},
        ),
        migrations.AlterModelOptions(
            name='roleassignment',
            options={'permissions': [('manage_role_grants', 'Can add or revoke scoped academic grants')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('reset_user_password', 'Can reset a user password with a reason')]},
        ),
    ]
