export type Assignment = {
  role: string;
  cycle_id: number;
  area_id: number | null;
};
export type User = {
  id: number;
  name: string;
  username: string;
  is_staff: boolean;
  can_view_security_audit: boolean;
  assignments: Assignment[];
};
export type Cycle = {
  id: number;
  title: string;
  program: string;
  instrument: string;
  status: string;
  is_demo: boolean;
  closed_at: string | null;
  can_close: boolean;
  can_reopen: boolean;
};
export type Summary = {
  total: number;
  overdue_count: number;
  complete: number;
  ready_for_completion_review: number;
  for_verification: number;
  needs_revision: number;
  in_progress: number;
  missing: number;
  excluded: number;
  percentage: number | null;
  formula: string;
  formula_version: number;
};
export type Area = Summary & {
  id: number;
  cycle: number;
  title: string;
  code: string;
  icon: string;
  order: number;
  can_manage: boolean;
  can_delete: boolean;
  can_upload: boolean;
};
export type Decision = {
  outcome: string;
  comment: string;
  reviewer: string;
  created_at: string;
};
export type Submission = {
  id: number;
  mapping: number;
  version: number;
  version_number: number;
  criteria_revision: number | null;
  legacy_submission_mode: boolean;
  document_title: string;
  document: string;
  original_name: string;
  checksum: string;
  valid_until: string | null;
  uploaded_by: string;
  item_label: string;
  requirement: number;
  requirement_title: string;
  submitted_at: string;
  submitted_by: string;
  status: string;
  current: boolean;
  can_review: boolean;
  decision: Decision | null;
};
export type Mapping = {
  id: number;
  document: string;
  document_title: string;
  item: number;
  submissions: Submission[];
};
export type Item = {
  id: number;
  label: string;
  criteria: string;
  mandatory: boolean;
  status: string;
  mappings: Mapping[];
};
export type Requirement = {
  id: number;
  code: string;
  title: string;
  description: string;
  area: number;
  area_title: string;
  cycle: number;
  icon: string;
  responsible: string;
  deadline: string | null;
  overdue: boolean;
  active: boolean;
  applicable: boolean;
  exclusion_reason: string;
  criteria_revision: number;
  legacy_certification: boolean;
  status: string;
  approved_items: number;
  required_items: number;
  can_manage: boolean;
  can_assign: boolean;
  can_upload: boolean;
  assignments?: RequirementAssignment[];
  can_complete?: boolean;
  can_reopen?: boolean;
  certifications?: Certification[];
  packages?: PackageAttempt[];
  package_choices?: PackageChoice[];
  package_certification_candidates?: PackageAttempt[];
  applicability_history?: ApplicabilityDecision[];
  certification_candidates?: CertificationEvidence[];
  items?: Item[];
};
export type RequirementAssignment = {
  id: number;
  user: number;
  name: string;
  username: string;
  active: boolean;
  assigned_by: string;
  created_at: string;
};
export type AssignmentCandidate = { id: number; name: string; username: string };
export type Certification = {
  id: number;
  outcome: "complete" | "reopened";
  coordinator: string;
  rationale: string;
  created_at: string;
  legacy: boolean;
  criteria_snapshot: { revision: number; code: string; title: string; cycle: number; area: number; instrument: string; description: string; items: Array<{ id: number; label: string; criteria: string; mandatory: boolean }> } | null;
  evidence: CertificationEvidence[];
  packages: Array<{ package: number; attempt: number; owner: number; criteria_revision: number; items: PackageItem[] }>;
};
export type PackageItem = {
  mapping: number; item: number; item_label: string; document: string; document_title: string;
  version: number; version_number: number; original_name: string; checksum: string;
  valid_until: string | null; note: string;
};
export type PackageChoice = Omit<PackageItem, "document" | "note">;
export type PackageAttempt = {
  id: number; requirement: number; requirement_title: string; number: number; owner: string; owner_id: number;
  source_attempt: number | null; source_attempt_number: number | null; status: "draft" | "submitted" | "approved" | "revisions_requested" | "withdrawn";
  requires_override: boolean;
  notes: string; criteria_revision: number | null; criteria_snapshot: Certification["criteria_snapshot"];
  withdrawal_reason: string; created_at: string; submitted_at: string | null; resolved_at: string | null;
  items: PackageItem[]; decision: Decision | null; can_edit: boolean; can_submit: boolean;
  can_withdraw: boolean; can_review: boolean; can_resubmit: boolean;
};
export type CertificationEvidence = {
  submission: number; item: number; item_label: string; document: string; document_title: string;
  submission_criteria_revision: number | null;
  version: number; version_number: number; original_name: string; checksum: string;
  valid_until: string | null; review_decision: number;
};
export type ApplicabilityDecision = { id: number; applicable: boolean; reason: string; coordinator: string; created_at: string };
export type Version = {
  id: number;
  number: number;
  original_name: string;
  content_type: string;
  size: number;
  checksum: string;
  uploaded_by: string;
  uploaded_at: string;
  valid_until: string | null;
  download_url: string;
  scan_status: "pending" | "clean" | "infected" | "error";
};
export type Document = {
  id: string;
  created_at: string;
  title: string;
  category: string;
  area: number;
  area_title: string;
  cycle: number;
  custodian: string;
  steward: string | null;
  steward_id: number | null;
  versions: Version[];
  can_upload: boolean;
  can_delegate_stewardship: boolean;
  mappings: Mapping[];
};
export type Audit = {
  id: number;
  actor: string;
  action: string;
  record: string;
  detail: Record<string, unknown>;
  area_id: number | null;
  actor_id: number | null;
  request_id: string;
  created_at: string;
};
export type AuditPage = { results: Audit[]; next_before: number | null; next_cursor?: string | null };
export type SearchResults = {
  requirements: Array<{ id: number; code: string; title: string; area: string; status: string }>;
  documents: Array<{ id: string; title: string; category: string; area: string }>;
  next_requirements?: number | null;
  next_documents?: string | null;
};
export type ComplianceReport = Summary & {
  numerator: number;
  denominator: number;
  filtered_row_count: number;
  population_label: string;
  calculated_at: string;
  timezone: string;
  scope: string;
  cycle: { id: number; title: string; instrument: string } | null;
  authorized_areas: Array<{ id: number; cycle_id: number; code: string; title: string }>;
  selected_filters: { cycle_id: number | null; area_id: number | null; area: string | null; status: string | null; overdue: boolean };
  rows: Array<{
    id: number;
    code: string;
    title: string;
    area: string;
    responsible: string;
    deadline: string | null;
    status: string;
    overdue: boolean;
    approved_items: number;
    required_items: number;
  }>;
};
