import { test, expect } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve("..");
const password = process.env.E2E_SYNTHETIC_PASSWORD || fs.readFileSync(path.join(root, ".local/demo-credentials.txt"), "utf8")
  .match(/Password for these fictional accounts: (.+)/)![1].trim();

test("archive and restore requirement and cycle without losing history", async ({ page }) => {
  await page.goto("/");
  await page.getByLabel("Email / Username").fill("demo.coordinator");
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign In", exact: true }).click();
  await expect(page.getByRole("heading", { name: /Welcome,/ })).toBeVisible();
  const cycle = await page.getByLabel("Accreditation cycle").inputValue();
  await page.getByRole("button", { name: "Requirements", exact: true }).click();
  const title = await page.locator("table tbody tr").first().locator("td strong").first().textContent();
  await page.locator("table tbody tr").first().getByRole("button", { name: /View/ }).click();
  await page.getByRole("button", { name: "Archive requirement" }).click();
  await expect(page.getByRole("dialog", { name: "Archive requirement" })).toBeVisible();
  await page.getByLabel("Reason for archiving").fill("Preserve completed pilot history.");
  await page.getByRole("dialog").getByRole("button", { name: "Archive requirement" }).click();
  await expect(page.getByRole("checkbox", { name: "Archived requirements" })).toBeChecked();
  await expect(page.locator("table tbody tr")).toHaveCount(1);
  await expect(page.locator("table tbody tr")).toContainText(title || "");
  await expect(page.locator("table tbody tr .badge.archived")).toHaveText("Archived");
  await page.locator("table tbody tr").getByRole("button", { name: /View/ }).click();
  await expect(page.locator(".requirement-summary")).toContainText("Preserve completed pilot history.");
  await expect(page.getByRole("heading", { name: "Archive history" })).toBeVisible();
  await page.getByRole("button", { name: "Reports", exact: true }).click();
  await page.getByRole("checkbox", { name: "Archived records" }).check();
  await expect(page.locator(".report-provenance")).toContainText("archive: Archived records");
  await expect(page.locator("table tbody tr .badge.archived")).toHaveText("Archived");
  const current = await (await page.request.get("/api/reports/compliance/?cycle=" + cycle)).json();
  const archived = await (await page.request.get("/api/reports/compliance/?cycle=" + cycle + "&archived=1")).json();
  expect(archived.rows).toHaveLength(1);
  expect(archived.denominator).toBe(current.denominator);
  await page.getByRole("button", { name: "Requirements", exact: true }).click();
  await page.locator("table tbody tr").getByRole("button", { name: /View/ }).click();
  await page.getByRole("button", { name: "Restore requirement" }).click();
  await page.getByLabel("Reason for restoring").fill("Return requirement to current monitoring.");
  await page.getByRole("dialog").getByRole("button", { name: "Restore requirement" }).click();
  await expect(page.getByRole("checkbox", { name: "Archived requirements" })).not.toBeChecked();
  await page.getByRole("button", { name: "Dashboard", exact: true }).click();
  await page.getByRole("button", { name: "Close cycle" }).click();
  await page.getByLabel("Reason for closing").fill("Pilot review is complete.");
  await page.getByRole("dialog").getByRole("button", { name: "Close cycle" }).click();
  await page.getByRole("button", { name: "Archive cycle" }).click();
  await page.getByLabel("Reason for archiving").fill("Preserve closed pilot cycle.");
  await page.getByRole("dialog").getByRole("button", { name: "Archive cycle" }).click();
  await expect(page.getByRole("checkbox", { name: "Show archived cycles" })).toBeChecked();
  await expect(page.getByText(/Archived cycle · Preserved records are read-only/)).toBeVisible();
  await page.getByRole("button", { name: "Restore cycle" }).click();
  await page.getByLabel("Reason for restoring").fill("Return to closed records.");
  await page.getByRole("dialog").getByRole("button", { name: "Restore cycle" }).click();
  await expect(page.getByText(/Closed cycle · Records are read-only/)).toBeVisible();
  await page.getByRole("button", { name: "Reopen cycle" }).click();
  await page.getByLabel("Reason for reopening").fill("Resume authorized work.");
  await page.getByRole("dialog").getByRole("button", { name: "Reopen cycle" }).click();
  await expect(page.getByRole("button", { name: "Close cycle" })).toBeVisible();
});
