import { test, expect, type Page } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve("..");
const password = process.env.E2E_SYNTHETIC_PASSWORD || fs.readFileSync(path.join(root, ".local/demo-credentials.txt"), "utf8")
  .match(/Password for these fictional accounts: (.+)/)![1].trim();
const samplePdf = process.env.E2E_SAMPLE_PDF || path.join(root, ".local/sample-evidence.pdf");

async function login(page: Page, role: string) {
  await page.goto("/");
  await page.getByLabel("Email / Username").fill(`demo.${role}`);
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign In", exact: true }).click();
  await expect(page.getByRole("heading", { name: /Welcome,/ })).toBeVisible();
  await ready(page);
}

async function ready(page: Page) {
  await expect(page.getByText("Updating records…")).toHaveCount(0, { timeout: 30000 });
}

async function openRequirement(page: Page, title: string) {
  await page.getByRole("button", { name: "Requirements", exact: true }).click();
  await ready(page);
  await page.getByRole("row").filter({ hasText: title })
    .getByRole("button", { name: "View", exact: true }).click();
}

test("login, scoped search and compliance report", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "MC Accreditation Hub" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.setViewportSize({ width: 1440, height: 900 });
  await login(page, "coordinator");
  await page.getByRole("button", { name: "Search", exact: true }).click();
  await page.getByLabel("Search all authorized records").fill("Faculty");
  await page.getByRole("button", { name: "Search", exact: true }).last().click();
  await expect(page.getByRole("heading", { name: "Requirements" })).toBeVisible();
  await page.getByRole("button", { name: "Reports", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Compliance Report" })).toBeVisible();
  await expect(page.getByRole("link", { name: /Export CSV/ })).toHaveAttribute("href", /download=csv/);
});

test("submitted package outranks missing evidence in the report", async ({ browser }) => {
  const title = `F07 precedence ${Date.now()}`;
  const documentTitle = `${title} evidence`;
  const coordinator = await browser.newPage();
  const custodian = await browser.newPage();
  await login(coordinator, "coordinator");
  await coordinator.getByRole("button", { name: "Requirements", exact: true }).click();
  await coordinator.getByRole("button", { name: "Add Requirement" }).click();
  const form = coordinator.getByRole("dialog");
  await form.getByRole("combobox", { name: "Accreditation area", exact: true }).selectOption({ label: "Faculty" });
  await form.getByLabel("Requirement code").fill(`F07-P-${Date.now()}`);
  await form.getByLabel("Requirement title").fill(title);
  await form.getByLabel("Responsible office / person").fill("Graduate School");
  await form.getByLabel("Evidence item 1").fill("Primary plan");
  await form.getByRole("button", { name: "Add evidence item" }).click();
  await form.getByLabel("Evidence item 2").fill("Missing attachment");
  await form.getByRole("button", { name: "Save Requirement" }).click();
  await coordinator.getByRole("row").filter({ hasText: title }).getByRole("button", { name: "View" }).click();
  const setupCycles = await (await coordinator.request.get("/api/cycles/")).json();
  const setupRequirements = await (await coordinator.request.get(`/api/requirements/?cycle=${setupCycles[0].id}`)).json();
  const setupRequirement = setupRequirements.find((requirement: { title: string }) => requirement.title === title);
  const assignmentData = await (await coordinator.request.get(`/api/requirements/${setupRequirement.id}/assignments/`)).json();
  const contributor = assignmentData.candidates.find((candidate: { username: string }) => candidate.username === "demo.custodian");
  expect(contributor).toBeTruthy();
  await coordinator.getByRole("button", { name: "Manage assignments" }).click();
  const assignment = coordinator.getByRole("dialog");
  await assignment.getByRole("combobox", { name: "Assigned contributor" }).selectOption(String(contributor.id));
  await assignment.getByRole("textbox", { name: "Assignment or reassignment reason" }).fill("F07 status test assignment.");
  await assignment.getByRole("button", { name: "Add assignee" }).click();
  await expect(assignment).toHaveCount(0);
  await coordinator.reload();
  await ready(coordinator);
  const cycleData = await (await coordinator.request.get("/api/cycles/")).json();
  const availableRequirements = await (await coordinator.request.get(`/api/requirements/?cycle=${cycleData[0].id}`)).json();
  expect(availableRequirements.some((requirement: { title: string; can_upload: boolean }) => requirement.title === title && requirement.can_upload)).toBe(true);
  await coordinator.getByRole("button", { name: "Evidence Repository" }).click();
  await coordinator.getByRole("button", { name: "Upload Document" }).click();
  const searchUpload = coordinator.getByRole("dialog");
  await searchUpload.getByLabel("Find requirement").fill(title);
  const requirementOptions = searchUpload.locator('select[name="requirement"] option');
  await expect(requirementOptions).toHaveCount(2);
  await expect(requirementOptions.last()).toContainText(title);
  await searchUpload.getByRole("button", { name: "Cancel" }).click();
  await login(custodian, "custodian");
  const custodianRequirements = await (await custodian.request.get(`/api/requirements/?cycle=${cycleData[0].id}`)).json();
  expect(custodianRequirements.some((requirement: { title: string; can_upload: boolean }) => requirement.title === title && requirement.can_upload)).toBe(true);
  await openRequirement(custodian, title);
  await custodian.getByRole("button", { name: "Upload evidence" }).first().click();
  const upload = custodian.getByRole("dialog");
  await upload.getByLabel("Document title").fill(`${title} evidence`);
  await upload.locator("input[type=file]").setInputFiles(samplePdf);
  await upload.getByRole("button", { name: "Upload & Map" }).click();
  await expect(upload).toHaveCount(0);
  await custodian.getByRole("button", { name: "Evidence Repository" }).click();
  const documentRow = custodian.getByRole("row").filter({ hasText: documentTitle });
  await documentRow.getByRole("button", { name: "View", exact: true }).click();
  const preview = custodian.locator('iframe[title^="Preview of"]');
  await expect(preview).toHaveAttribute("src", /\/api\/document-versions\/\d+\/preview\//);
  const previewUrl = await preview.getAttribute("src");
  const previewResponse = await custodian.request.get(previewUrl!);
  expect(previewResponse.status()).toBe(200);
  expect(previewResponse.headers()["content-disposition"]).toMatch(/^inline/i);
  await custodian.getByRole("button", { name: "All documents" }).click();
  await openRequirement(custodian, title);
  await custodian.getByRole("button", { name: "New package draft" }).click();
  const draft = custodian.getByRole("dialog");
  await draft.getByRole("checkbox", { name: /Include Primary plan/ }).check();
  await draft.getByRole("button", { name: "Save draft" }).click();
  await expect(draft).toHaveCount(0);
  await custodian.getByRole("button", { name: "Submit package" }).click();
  await expect(custodian.locator(".requirement-summary").getByText("For Verification", { exact: true })).toBeVisible({ timeout: 30000 });
  await coordinator.reload();
  await ready(coordinator);
  await openRequirement(coordinator, title);
  await expect(coordinator.locator(".requirement-summary").getByText("For Verification", { exact: true })).toBeVisible();
  await coordinator.getByRole("button", { name: "Reports", exact: true }).click();
  await coordinator.getByRole("combobox", { name: "Status" }).selectOption("for_verification");
  const row = coordinator.getByRole("row").filter({ hasText: title });
  await expect(row).toContainText("For Verification", { timeout: 30000 });
  await expect(row).toContainText("0/2");
  await Promise.all([coordinator.context().close(), custodian.context().close()]);
});

test("package attempts preserve draft, withdrawal, revision, review and certification history", async ({ browser }) => {
  const title = `F07 browser ${Date.now()}`;
  const documentTitle = `${title} evidence`;
  const coordinatorContext = await browser.newContext();
  const custodianContext = await browser.newContext();
  const reviewerContext = await browser.newContext();
  const viewerContext = await browser.newContext();
  const coordinator = await coordinatorContext.newPage();
  const custodian = await custodianContext.newPage();
  const reviewer = await reviewerContext.newPage();
  const viewer = await viewerContext.newPage();
  const errors: string[] = [];
  for (const page of [coordinator, custodian, reviewer, viewer]) page.on("pageerror", error => errors.push(error.message));
  await login(coordinator, "coordinator");
  await coordinator.getByRole("button", { name: "Requirements", exact: true }).click();
  await coordinator.getByRole("button", { name: "Add Requirement", exact: true }).click();
  const requirementForm = coordinator.getByRole("dialog");
  await requirementForm.getByRole("combobox", { name: "Accreditation area", exact: true }).selectOption({ label: "Faculty" });
  await requirementForm.getByLabel("Requirement code").fill(`F07-${Date.now()}`);
  await requirementForm.getByLabel("Requirement title").fill(title);
  await requirementForm.getByLabel("Description / acceptance criteria").fill("A signed faculty plan.");
  await requirementForm.getByLabel("Responsible office / person").fill("Graduate School");
  await requirementForm.getByLabel("Evidence item 1").fill("Faculty plan");
  await requirementForm.getByLabel("Acceptance criteria", { exact: true }).fill("Readable signed plan.");
  await requirementForm.getByRole("button", { name: "Save Requirement" }).click();
  await coordinator.getByRole("row").filter({ hasText: title }).getByRole("button", { name: "View", exact: true }).click();
  await coordinator.getByRole("button", { name: "Manage assignments" }).click();
  const assignment = coordinator.getByRole("dialog");
  await assignment.getByRole("combobox", { name: "Assigned contributor" }).selectOption({ index: 1 });
  await assignment.getByRole("textbox", { name: "Assignment or reassignment reason" }).fill("F07 package test assignment.");
  await assignment.getByRole("button", { name: "Add assignee" }).click();

  await login(custodian, "custodian");
  await openRequirement(custodian, title);
  await custodian.getByRole("button", { name: "Upload evidence" }).click();
  const upload = custodian.getByRole("dialog");
  await upload.getByLabel("Document title").fill(documentTitle);
  await upload.locator("input[type=file]").setInputFiles(samplePdf);
  await upload.getByRole("button", { name: "Upload & Map" }).click();
  await expect(upload).toHaveCount(0);
  await custodian.getByRole("button", { name: "New package draft" }).click();
  let editor = custodian.getByRole("dialog");
  await expect(editor.getByText("Readable signed plan.")).toBeVisible();
  await editor.getByLabel("Package notes").fill("First attempt notes");
  await editor.getByRole("checkbox", { name: /Include Faculty plan/ }).check();
  await expect(editor.getByLabel("Exact version for Faculty plan")).toContainText("SHA-256");
  await editor.getByLabel("Evidence note").fill("Selected exact draft version");
  await editor.getByRole("button", { name: "Save draft" }).click();
  await expect(editor).toHaveCount(0);
  await custodian.reload();
  await ready(custodian);
  await openRequirement(custodian, title);
  await expect(custodian.locator(".requirement-summary").getByText("In Progress", { exact: true })).toBeVisible();
  await custodian.getByRole("button", { name: "Edit draft" }).click();
  editor = custodian.getByRole("dialog");
  await editor.getByLabel("Package notes").fill("Edited before submission");
  await editor.getByRole("button", { name: "Save draft" }).click();
  await expect(custodian.getByText("Edited before submission")).toBeVisible();
  await custodian.getByRole("button", { name: "Submit package" }).click();
  await expect(custodian.locator(".requirement-summary").getByText("For Verification", { exact: true })).toBeVisible();

  await login(reviewer, "reviewer");
  await reviewer.getByRole("button", { name: "Evidence Verification" }).click();
  await expect(reviewer.getByRole("row").filter({ hasText: title })).toContainText("1 pinned versions");
  await login(viewer, "viewer");
  await viewer.getByRole("button", { name: "Evidence Repository" }).click();
  await expect(viewer.getByText(documentTitle, { exact: true })).toHaveCount(0);

  custodian.once("dialog", dialog => dialog.accept());
  await custodian.getByRole("button", { name: "Withdraw package" }).click();
  await expect(custodian.getByText("Attempt 1")).toBeVisible();
  await custodian.getByRole("button", { name: "Create resubmission draft" }).click();
  await expect(custodian.getByText("Resubmitted from attempt #1")).toBeVisible();
  await custodian.getByRole("button", { name: "Submit package" }).click();
  await expect(custodian.locator(".requirement-summary").getByText("For Verification", { exact: true })).toBeVisible({ timeout: 30000 });
  await reviewer.reload();
  await ready(reviewer);
  await reviewer.getByRole("button", { name: "Evidence Verification" }).click();
  const secondQueueRow = reviewer.getByRole("row").filter({ hasText: title }).filter({ hasText: "#2" });
  await expect(secondQueueRow).toBeVisible({ timeout: 30000 });
  const reviewPackageButton = secondQueueRow.getByRole("button", { name: "Review package" });
  await reviewPackageButton.click();
  let review = reviewer.getByRole("dialog");
  await expect(review).toHaveAttribute("aria-labelledby");
  await expect(review.locator("h2")).toBeFocused();
  const closeReview = review.getByRole("button", { name: "Close dialog" });
  await reviewer.keyboard.press("Tab");
  await expect(closeReview).toBeFocused();
  await reviewer.keyboard.press("Shift+Tab");
  expect(await review.evaluate((dialog) => dialog.contains(document.activeElement))).toBeTruthy();
  await reviewer.keyboard.press("Tab");
  await expect(closeReview).toBeFocused();
  await reviewer.keyboard.press("Escape");
  await expect(review).toHaveCount(0);
  await expect(reviewPackageButton).toBeFocused();
  await reviewPackageButton.click();
  review = reviewer.getByRole("dialog");
  await expect(review.getByText(/Submitted criteria snapshot · revision 1/)).toBeVisible();
  await expect(review.getByText(/Current criteria · revision 1/)).toBeVisible();
  await expect(review.getByText(/Package owner:/)).toBeVisible();
  await expect(review.getByText(/valid until No expiry/)).toBeVisible();
  await expect(review.getByRole("combobox", { name: "Decision" })).toHaveValue("");
  await expect(review.getByRole("button", { name: "Record package decision" })).toBeDisabled();
  await review.getByRole("combobox", { name: "Decision" }).selectOption("revisions_requested");
  await review.getByLabel(/Review comments/).fill("Add a signature note.");
  await review.getByRole("button", { name: "Record package decision" }).click();
  await custodian.reload();
  await ready(custodian);
  await openRequirement(custodian, title);
  await expect(custodian.locator(".requirement-summary").getByText("Needs Revision", { exact: true })).toBeVisible();
  await custodian.getByRole("button", { name: "Create resubmission draft" }).first().click();
  await custodian.getByRole("button", { name: "Edit draft" }).click();
  editor = custodian.getByRole("dialog");
  await editor.getByLabel("Package notes").fill("Signed plan submitted again");
  await editor.getByRole("button", { name: "Save draft" }).click();
  await custodian.getByRole("button", { name: "Submit package" }).click();
  await expect(custodian.locator(".requirement-summary").getByText("For Verification", { exact: true })).toBeVisible({ timeout: 30000 });
  await reviewer.reload();
  await ready(reviewer);
  await reviewer.getByRole("button", { name: "Evidence Verification" }).click();
  const thirdQueueRow = reviewer.getByRole("row").filter({ hasText: title }).filter({ hasText: "#3" });
  await expect(thirdQueueRow).toBeVisible({ timeout: 30000 });
  await thirdQueueRow.getByRole("button", { name: "Review package" }).click();
  review = reviewer.getByRole("dialog");
  await expect(review.getByText(/Prior attempt 2:/)).toBeVisible();
  await expect(review.getByRole("combobox", { name: "Decision" })).toHaveValue("");
  await expect(review.getByRole("button", { name: "Record package decision" })).toBeDisabled();
  await review.getByRole("combobox", { name: "Decision" }).selectOption("approved");
  await review.getByRole("button", { name: "Record package decision" }).click();
  await coordinator.reload();
  await ready(coordinator);
  await openRequirement(coordinator, title);
  await expect(coordinator.getByRole("heading", { name: "Ready for Completion Review" })).toBeVisible();
  await expect(coordinator.getByText("Attempt 1")).toBeVisible();
  await expect(coordinator.getByText("Attempt 2")).toBeVisible();
  await expect(coordinator.getByText("Attempt 3")).toBeVisible();
  await coordinator.getByRole("button", { name: "Mark Complete" }).click();
  const cert = coordinator.getByRole("dialog");
  await expect(cert.getByText(/Approved package attempt 3/)).toBeVisible();
  await cert.getByLabel("Rationale").fill("Selected approved package with current criteria.");
  await cert.getByRole("checkbox").check();
  await cert.getByRole("button", { name: "Mark Complete" }).click();
  await expect(cert).toHaveCount(0);
  await expect(coordinator.getByText(/Selected package attempt 3/)).toBeVisible({ timeout: 30000 });
  await viewer.reload();
  await viewer.getByRole("button", { name: "Evidence Repository" }).click();
  await expect(viewer.getByText(documentTitle, { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
  await Promise.all([coordinatorContext.close(), custodianContext.close(), reviewerContext.close(), viewerContext.close()]);
});
